# _config.yml

title: "ğŸ™Podcast Generator ğŸ™"
description: "Transformez vos scripts en podcasts multi-voix captivants"
url: "https://laurentftech.github.io/Podcast_generator"

# Langue par dÃ©faut
lang: fr

# Layout par dÃ©faut si non prÃ©cisÃ©
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Plugins utiles (GitHub Pages en supporte une liste limitÃ©e)
plugins:
  - jekyll-seo-tag   # AmÃ©liore le rÃ©fÃ©rencement SEO
  - jekyll-sitemap   # GÃ©nÃ¨re un sitemap.xml automatiquement

# Exclusions (fichiers Ã  ne pas publier)
exclude:
  - Gemfile
  - Gemfile.lock
